name: Build & Deploy

on:
  push:
    branches:  
      - main 
      - master
    paths-ignore:
      - '**/README.md'


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build static files
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build
      
      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: fiitteam8/ams_team_documentation
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
    - name: Executing remote ssh docker deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_MACHINE }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          cd /home/fiitkar/data_infrastructure
          docker-compose pull documentation && docker-compose --env-file env/elastic_infrastructure.env up -d --no-deps --build documentation && docker system prune -f
